spring.application.name=demo

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ChatSockets}
spring.datasource.username=${DB_USERNAME:chat_app}
spring.datasource.password=${DB_PASSWORD:Admin123*}
jwt.secret=una-clave-secreta-larga-y-segura
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

